# Describes the format for available Spotify services
set_timeframe:
  fields:
    time_unit:
      example: days
      required: true
      selector:
        select:
          options:
            - "days"
            - "weeks"

    timeframe:
      example: 7
      required: true
      selector:
        number:
          min: 1
          max: 150
          unit_of_measurement: days
