# Describes the format for available Spotify services

set_timeframe:
  fields:
    timeframe:
      example: 7
      required: true
      selector:
        number:
          min: 1
          max: 150
          unit_of_measurement: days
