# Describes the format for available Spotify services
set_timeframe:
  fields:
    timeframe:
      example: 7
      required: true
      selector:
        number:
          min: 1
          max: 52
          mode: slider
    time_unit:
      example: "days"
      required: true
      selector:
        select:
          options:
            - "days"
            - "weeks"
            - "months"
